default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 4

development: &development
  <<: *default
  pool: 5
  url: postgres://treinarme:fA7XDjjq88V99e4KXyoQRT97N4a6ad@treinarme-rds.cmvunrtfqlm8.us-east-1.rds.amazonaws.com:5432/treinarme_mvp_production?sslca=config/rds-ssl-ca-cert.pem&sslmode=require&encrypt=true

production:
  <<: *default
  pool: 15
  url: postgres://treinarme:fA7XDjjq88V99e4KXyoQRT97N4a6ad@treinarme-rds.cmvunrtfqlm8.us-east-1.rds.amazonaws.com:5432/treinarme_mvp_production?sslca=config/rds-ssl-ca-cert.pem&sslmode=require&encrypt=true
